#
# This file contains configuration flags to customize Bronte Sihan Li's website on Github
#

title: FireSight - AI Insight on Wildfire Impact

# Short bio or description (displayed in the header)
description:  DREAM 2023 | Wildfire Spread Prediction in North America Using Satellite Imagery and Vision Transformer

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://bronteee.github.io/images/headshot.JPG

heroimage: /images/wildfire.avif

project-intro: Wildfires are growing more severe each year, fueled by climate change, urban development, and other factors. These increasingly devastating fires put communities, wildlife, and landscapes at great risk. Accurately modeling the ignition, spread, and impact of wildfires is crucial for protecting lives and property. That's why innovative artificial intelligence systems are needed to analyze diverse variables and make reliable predictions about fire growth and behavior. AI can rapidly process satellite imagery, weather data, vegetation maps, and more to generate high-resolution wildfire models. These AI-powered simulations enable firefighters and officials to strategically deploy resources and issue targeted evacuation warnings. With explainable AI, predictions also become more transparent and auditable. Overall, harnessing the power of AI is essential for communities to better prepare for and respond to the wildfire threat, directing prevention resources where they're needed most and keeping our most vulnerable populations out of harm's way. Advanced AI represents our best hope for averting wildfire catastrophes through early warnings and actionable insights.

project-about: This is one of the research projects initiated by the Distributed REsearch Apprenticeships for Master's (DREAM) program by Computing Research Association. 

# Name of the Author
author-name: Bronte Sihan Li
# URL for the Image of the Author
author-image: https://bronteee.github.io/images/headshot.JPG
# 60 Words About the Author
author-about: Bronte found her passion in artificial intelligence and research while working as a senior medical laboratory scientist at Seattle Children's and then at a digital health AI startup after pursuing a master's degree in Computer Science at Northeastern University (2022-2023). She helped develop and perform high complexity diagnostic testing, including one of the first COVID-19 PCR tests in Seattle. This experience sparked her interest in using AI to improve healthcare technology and make it more accessible. Now Bronte is excited to pursue interdisciplinary AI research that can benefit under-served populations. She brings a unique perspective with her background spanning AI, medicine, and public health. In her free time, Bronte enjoys traveling, doing CrossFit with friends, and yoga. Her interdisciplinary knowledge helps inform creative solutions at the intersection of AI and healthcare.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://www.linkedin.com/in/brontesihanli/

advisor-image: /images/ryan_rad.png

advisor-about: Dr. Ryan Rad is an assistant professor in the Khoury College of Computer Sciences at Northeastern University in Vancouver. In industry, he worked as a researcher, engineer, team lead, and product manager for several startups and companies, including Microsoft. Ryan has led several data analytics and machine learning research projects delivering innovative, responsible, and cutting-edge AI solutions to the enterprise, leveraging machine learning and computer vision to benefit communities from healthcare to sustainability. He served as a technical committee member or speaker for several top-tier computer science journals and conferences including IEEE TIP, IEEE TMI, ICCV, ICIP, VCIP, AAAI, and MICCAI. Ryan primarily teaches Machine Learning, Algorithms, Software Engineering, and Data Analytics & visualization. His current research focus lies at the intersection of computer vision and AI/ML, with a strong emphasis on environmental sustainability.

advisor-url: https://www.khoury.northeastern.edu/home/rrad/

advisor-email: r.rad@northeastern.edu


email: li.siha [at] northeastern [dot] edu
linkedin_username: brontesihanli
github: https://github.com/bronteee

# Your website URL (e.g. http://ajstent.github.io)
# Used for Sitemap.xml and your RSS feed
url: https://bronteee.github.io/

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: "/firesight"

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Compress
compress_html:
  clippings: all

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/


# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  sass_dir: _sass
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

theme: jekyll-theme-cayman

background-image: url('/images/background.jpeg')

background: background.jpeg


# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - Machine Learning
        - Wildfire
        - AI
  -
    scope:
      type: 'pages'
    values:
      layout: page